version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    source-branch: develop
    target-branch: develop
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /
    source-branch: develop
    target-branch: develop
    schedule:
      interval: weekly
