on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
name: ci
jobs:
  check:
    uses: truemark/github-workflows/.github/workflows/terraform-module-check.yml@main
