on:
  pull_request:
  issues:
    types:
      - opened
name: issues
jobs:
  add-to-project:
    name: Add issue to project
    if: github.actor != 'dependabot[bot]'
    uses: truemark/github-workflows/.github/workflows/issues.yml@main
    secrets:
      private-key: ${{ secrets.ISSUES_BOT_KEY }}
      app-id: ${{ secrets.ISSUES_BOT_ID }}
